name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

trigger:
  branches:
    include:
      - master
      - prod
      - "hotfix/*"

pool:
  vmImage: "ubuntu-18.04"

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    newDeployTag: $(Build.BuildNumber)
    deployRepoRef: master
    imageTags: |
      $(Build.BuildNumber)
  ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}:
    newDeployTag: stable-$(Build.BuildNumber)
    deployRepoRef: prod
    imageTags: |
      stable-$(Build.BuildNumber)
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/hotfix') }}:
    newDeployTag: hotfix-$(Build.BuildNumber)
    deployRepoRef: $(Build.SourceBranch)
    imageTags: |
      hotfix-$(Build.BuildNumber)

  # pipelines require that all repositories are accessible before you ever use them.
  # Since we want to push tag changes from master to master (and develop to develop)
  # but do NOT want to push tag changes on PR branches, we simply set the deploy repo
  # branch to master. We won't use it anyway.
  ${{ if eq(variables['deployRepoRef'], '') }}:
    deployRepoRef: master

resources:
  repositories:
    - repository: deploy-morphic-community-web
      type: github
      endpoint: oregondesignservices
      name: oregondesignservices/deploy-morphic-community-web
      ref: $(deployRepoRef)

stages:
  -
    stage: build
    displayName: Build
    jobs:
      -
        job: build
        displayName: Build
        steps:
          - task: Docker@2
            displayName: login to morphicworld dockerhub account
            inputs:
              command: login
              containerRegistry: morphicworld dockerhub
          - task: Docker@2
            displayName: Build & Push Docker Image
            inputs:
              command: buildAndPush
              dockerfile: Dockerfile
              repository: morphicworld/morphic-community-web
              tags: $(Build.BuildNumber)
              arguments: "--build-arg 'BUNDLE_VERSION=$(Build.BuildNumber)'"

  - stage: update_deploy_tag
    jobs:
      - job: update_deploy_tag
        condition: ne(variables['newDeployTag'], '')
        steps:
          - checkout: deploy-morphic-community-web
            persistCredentials: true
            path: deploy-morphic-community-web
          - task: Bash@3
            env:
              NEWTAG: $(newDeployTag)
              BRANCH: $(deployRepoRef)
            inputs:
              targetType: 'inline'
              workingDirectory: base/
              script: |
                set -e
                set -x
                echo "installing kustomize"
                wget "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" -O install_kustomize.sh
                bash install_kustomize.sh

                git checkout ${BRANCH}

                ls -al
                echo "setting new image tag"
                ./kustomize edit set image morphicworld/morphic-community-web=morphicworld/morphic-community-web:${NEWTAG}

                cat kustomization.yaml

                git config --global user.email "buildmaster@raisingthefloor.org"
                git config --global user.name "buildmaster"
                git commit kustomization.yaml -m "buildmaster: updating tag to ${NEWTAG}"
                git push
