name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:r)

trigger:
  branches:
    include:
      - master
      - release/*
      - staging/*

pool:
  vmImage: "ubuntu-18.04"

variables:
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    envfile: buildenv/development.env
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/staging/') }}:
    envfile: buildenv/staging.env
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    envfile: buildenv/production.env

stages:
  -
    stage: build
    displayName: Build
    jobs:
      -
        job: build
        displayName: Build
        steps:
          -
            task: NodeTool@0
            displayName: Install Node
            inputs:
              versionSpec: 12.x
          -
            task: Docker@2
            displayName: Install Docker
            inputs:
              command: login
              containerRegistry: morphicworld dockerhub
          -
            script: npm install --production=false
            displayName: Install Development Tools
          -
            script: npx jskit make MorphicCommunityWeb --no-tag --bundle-version $(Build.BuildNumber) --env $(envfile)
            displayName: Build MorphicCommunityWeb
          -
            task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: push
              repository: morphicworld/morphiccommunityweb
              tags: $(Build.BuildNumber)