File's Owner: /ViewController

ViewController:
  class: CommunityBillingSettingsViewController
  view:
    subviews:
      - /CreditCardField
      - /SubscribeButton
  outlets:
    creditCardField: /CreditCardField
    subscribeButton: /SubscribeButton

CreditCardField:
  class: CreditCardField
  borderWidth: 1
  borderColor: black
  maskedBorders: maxY

SubscribeButton:
  class: UIButton
  styler:
    class: UIButtonCustomStyler
    normalBackgroundColor:
      rgba: 0,129,69
    normalTitleColor: white
    titleInsets: 3,7
    cornerRadius: 2
  title: Subscribe