File's Owner: /ViewController

ViewController:
  class: CommunityBillingSettingsViewController
  view:
    subviews:
      - /ScrollView
      - /ErrorView
  outlets:
    syncIndicator: /SyncIndicator
    scrollView: /ScrollView
    errorView: /ErrorView
    plansView: /PlansView
    trialStatusLabel: /TrialStatusLabel
    paymentErrorLabel: /PaymentErrorLabel
    formView: /FormView
    contactPopupButton: /ContactPopupButton
    cardValueView: /CardValueView
    cardValueLabel: /CardValueLabel
    cardValueButton: /CardValueButton
    accountValueView: /AccountValueView
    accountValueLabel: /AccountValueLabel
    closeAccountButton: /CloseAccountButton

SyncIndicator:
  class: SyncIndicator
  errorTooltip: .syncError.tooltip
  target: /ViewController
  action: resync
  bindings:
    state: {to: /ViewController, value: billingSaveSynchronizer.state}

ScrollView:
  class: UIScrollView
  hidden: true
  subviews:
    - /PlansView
    - /TrialStatusLabel
    - /PaymentErrorLabel
    - /FormView

ErrorView:
  class: UILabel
  text: .error.text
  textInsets: 0,40
  lines: 0
  hidden: true
  font:
    size: detail
  textColor:
    rgba: 128,128,128

TrialStatusLabel:
  class: UILabel
  lines: 0
  textInsets: 0,0,10,0
  textAlignment: center
  textColor:
    rgba: 102,102,102
  font:
    weight: regular

PaymentErrorLabel:
  class: UILabel
  lines: 0
  textInsets: 0,0,10,0
  textAlignment: center
  textColor:
    rgba: 129,43,0
  font:
    weight: regular
  text: .paymentError.text

PlansView:
  class: UIStackView
  axis: horizontal
  viewSpacing: 10
  distribution: equal

FormView:
  class: FormView
  labelSpacing: 10
  fieldSpacing: 10
  fields:
    -
      label: /CardLabel
      view: /CardValueView
    -
      label: /ContactLabel
      view: /ContactPopupButton
    -
      label: /AccountLabel
      view: /AccountValueView

CardLabel:
  class: UILabel
  text: .card.text
  textAlignment: right

CardValueView:
  class: CommunityBillingCardField
  label: /CardValueLabel
  button: /CardValueButton

CardValueLabel:
  class: UILabel
  textInsets: 0,0,0,7

CardValueButton:
  class: UIButton
  styler:
    class: UIButtonCustomStyler
    normalBackgroundColor:
      rgba: 0,129,69
    normalTitleColor: white
    titleInsets: 3,7
    cornerRadius: 2
  target: /ViewController
  action: changeCard
  title: ""

ContactLabel:
  class: UILabel
  text: .contact.text
  textAlignment: right

ContactPopupButton:
  class: UIPopupButton
  target: /ViewController
  action: contactChanged

AccountLabel:
  class: UILabel
  text: .account.text
  textAlignment: right

AccountValueView:
  class: CommunityBillingAccountField
  label: /AccountValueLabel
  button: /CloseAccountButton

AccountValueLabel:
  class: UILabel
  text: ""

CloseAccountButton:
  class: UIButton
  styler:
    class: UIButtonCustomStyler
    normalBackgroundColor:
      rgba: 0,129,69
    normalTitleColor: white
    titleInsets: 3,7
    cornerRadius: 2
  title: .account.closeButton.title
  action: closeAccount
  target: /ViewController