File's Owner: /ViewController

ViewController:
  class: CommunityGeneralSettingsViewController
  view:
    subviews:
      - /ScrollView
  outlets:
    scrollView: /ScrollView
    form: /Form
    nameField: /NameField
    membersValueLabel: /MembersValueLabel

ScrollView:
  class: UIScrollView
  subviews:
    - /Form

Form:
  class: FormView
  labelSpacing: 10
  fieldSpacing: 10
  fields:
    -
      label: /NameLabel
      view: /NameField
    -
      label: /MembersLabel
      view: /MembersValueLabel

NameLabel:
  class: UILabel
  text: .fields.name.label
  textAlignment: right

NameField:
  class: UITextField
  bindings:
    text: {to: /ViewController, value: community.name}
  target: /ViewController
  action: nameChanged

MembersLabel:
  class: UILabel
  text: .fields.members.label
  textAlignment: right

MembersValueLabel:
  class: UILabel
  text: ""