File's Owner: /ViewController

ViewController:
  class: CommunityGeneralSettingsViewController
  view:
    subviews:
      - /ScrollView
  outlets:
    scrollView: /ScrollView
    form: /Form
    nameField: /NameField

ScrollView:
  class: UIScrollView
  subviews:
    - /Form

Form:
  class: FormView
  labelSpacing: 10
  fields:
    -
      label: /NameLabel
      view: /NameField

NameLabel:
  class: UILabel
  text: .fields.name.label

NameField:
  class: UITextField
  bindings:
    text: {to: /ViewController, value: community.name}
  target: /ViewController
  action: nameChanged