en:
  window.title: Community Settings
  categories:
    general.title: General
    permissions.title: Permissions
    billing.title: Billing
  syncError.tooltip:  Sorry, we couldn't save your last change.  Click to retry.